name: Download Habbo Files
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      # articles
      - name: Download News Article Images
        run: node src/index.js -c articles

      # badgeparts
      - name: Download Badgeparts Images
        run: node src/index.js -c badgeparts

      # badges
      - name: Download Badges
        run: node src/index.js -c badges

      # clothes
      - name: Download Clothes
        run: node src/index.js -c clothes

      # effects
      - name: Download Effects
        run: node src/index.js -c effects

      # ficons
      - name: Download Furniture Icons
        run: node src/index.js -c ficons

      # furnitures
      - name: Download Furnitures
        run: node src/index.js -c furnitures

      # gamedata
      - name: Download Gamedata Files
        run: node src/index.js -c gamedata

      # gordon
      - name: Download Gordon Files
        run: node src/index.js -c gordon

      # habboswf
      - name: Download Habbo.swf
        run: node src/index.js -c habboswf

      # hotelview
      - name: Download Hotelview Images
        run: node src/index.js -c hotelview

      # icons
      - name: Download Catalogue Icons
        run: node src/index.js -c icons

      # mp3
      - name: Download MP3 Files (sound_machine_sample)
        run: node src/index.js -c mp3

      # pets
      - name: Download Pets
        run: node src/index.js -c pets

      # promo
      - name: Download Web Promo Images
        run: node src/index.js -c promo

      # commit
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: resource
