name: Convert Habbo Files
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      # Convert XML to JSON
      - name: Convert ExternalTexts XML to JSON
        run: |
        git clone https://github.com/billsonnn/nitro-converter.git ./bundler
        cd ./bundler
        yarn install
        yarn build
        cp ../scripts/configuration.json /configuration.json
        yarn start
        mv /assets ../
             

      # commit
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: resource
