name: Convert Habbo Files
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      # Convert XML to JSON
      - name: Convert ExternalTexts XML to JSON
        run: node ./scripts/externalTextsToJson.js

      # commit
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: resource
