name: Convert Habbo Files
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      - name: Run Bundler
        run: |
          cd ./bundler
          yarn install
          yarn build
          yarn start

      # commit
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: resource
